# Generated by Django 5.2.17 on 2026-09-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
