# Generated by Django 5.2.17 on 2026-09-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticketattachment_escalated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketattachment',
            name='escalated',
        ),
        migrations.RemoveField(
            model_name='ticketattachment',
            name='escalated_at',
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
